name: Selenium CI

# Run workflow on schedule (cron)
on:
  schedule:
    - cron: '0 2-8 * * *'  # Adjust to your timezone, GitHub uses UTC
  workflow_dispatch: # allows manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (optional, useful for multi-stage builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t selenium-java-test .

      # 4. Run tests in Docker container
      - name: Run tests
        run: |
          docker run --rm selenium-java-test
