name: Selenium CI

# Run workflow on schedule (cron) or manually
on:
  schedule:
    - cron: '0 * * * *'  # runs at minute 0 of every hour (UTC)
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Build Maven test Docker image
      - name: Build Docker image
        run: |
          docker build -t selenium-java-test .

      # 4️⃣ Run tests in Docker container
      - name: Run tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
        run: |
          docker run --rm --env SELENIUM_URL=$SELENIUM_URL selenium-java-test
