name: Selenium Tests

# Run every hour
on:
  schedule:
    - cron: '0 * * * *'  # At minute 0 every hour
  workflow_dispatch:      # Allows manual trigger too

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Maven Selenium Docker image
        run: docker build -t maven-selenium-test .
          
          # ✅ Wait for Selenium to be ready
               - name: Wait for Selenium
               run: |
                 for i in {1..30}; do
                   curl -s http://selenium:4444/wd/hub/status && break
                   echo "Waiting for Selenium..."
                   sleep 2
                 done

      - name: Run Maven tests
        run: docker run --rm --network host -e SELENIUM_URL=http://selenium:4444/wd/hub maven-selenium-test mvn test
