name: Selenium Tests

# Run every hour
on:
  schedule:
    - cron: '0 * * * *'  # At minute 0 every hour
  workflow_dispatch:      # Allows manual trigger too
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t maven-selenium-test .

      # 4. Run Selenium tests
      - name: Run Selenium tests
        run: |
          mkdir -p $GITHUB_WORKSPACE/target
          docker run -v $GITHUB_WORKSPACE/target:/app/target maven-selenium-test

      # 5. Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/